

service: check-it-out-backend


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

functions:
  hello:
    handler: handler.checkitout

 environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}

  events:
      - http:
          path: itemstatus/{item}
          method: get
          cors: true
      - http:
          path: addstatus/{item}/{store}/{status}
          method: post
          cors: true 